### ISSUE TITLE
Actual working demo

### ISSUE THREAD

**Issue by nddrylliog** [audiocogs/alac.js#2]
I heard from @devongovett (on IRC I believe) that it was working - but can we have a demo with audio and all? Maybe work with @quinnirill to have an audio sink. @JensNockert I know you've been busy with school and all, but this is a priority right now, so if we can all just pitch in and make it happen quickly.

The goal right now is to quickly get up a page ie. codecs.ofmlabs.org where we have both jsmad and alac.js side-by-side, running on the same audio sample, and later on we can add how much time/CPU it takes to decode both formats, maybe measure the error induced by MP3, the size ratios, interesting stuff like that.

But first, run two working demos side-by-side. Quickly.

**Comment by devongovett** [comment]
Not quite there yet... part of the decoder is unfinished, and we haven't tested it.  Demo is a little farther off than I originally thought.

**Comment by devongovett** [comment]
Well we have a working demo now. Closing.

**Comment by nddrylliog** [comment]
:)
