### ISSUE TITLE
Workers

### ISSUE THREAD

**Issue by devongovett** [audiocogs/alac.js#3]
So I got worker decoding working YAY! Chrome plays buttery smooth audio as of 31d07fb no stutters or anything.  And now we have Firefox bugs to deal with.  Firefox 8 doesn't support XHR array buffer responses inside Web Workers (let alone not supporting local hosted workers at all)... Both of those issues are fixed in Aurora but I keep getting buffer underflow errors from Sink.js.  So perhaps we should only do the worker thing in Chrome and keep everything in the main thread for Firefox?  What do you think.

Living on the cutting edge is ugly sometimes. :(

**Comment by devongovett** [comment]
Or we could try to keep doing the decoding in the worker but do the XHRs in the main thread... but I'm not sure it's worth it.

**Comment by devongovett** [comment]
But it seems even the non-worker version fails with that underflow issue in Aurora, so not specific to the worker stuff.

**Comment by auroranockert** [comment]
I'm looking into the audio issues on Aurora tonight. Also, isn't it very late for you Devon?

**Comment by devongovett** [comment]
Nah, not too bad... Only 1:25.  So what about the XHR thing?

**Comment by devongovett** [comment]
Firefox 8 works well on the streaming branch but not the worker branch.  Chrome is the other way around.

**Comment by devongovett** [comment]
It does really bog down the Firefox UI though...

**Comment by devongovett** [comment]
Huh... alright. I think I'll look into doing the XHRs on the main thread tomorrow.  Going to bed now.  Night!

**Comment by auroranockert** [comment]
Detect browser and
Load different branches?

**Comment by auroranockert** [comment]
Good night!

**Comment by nddrylliog** [comment]
![](http://memegenerator.net/cache/instances/400x/11/11708/11989654.jpg)

Yup, that's me.

**Comment by devongovett** [comment]
Fixed the XHR issue by making my own buffers from xhr.responseText.  Not too big a deal since it is fixed in Aurora.

**Comment by devongovett** [comment]
I've run out of ideas on how to fix the buffer underflow issue... If you can figure it out, I will be eternally grateful!

**Comment by auroranockert** [comment]
I'll look at it, was intending to, but I just cannot think today, sorry.

I hope I feel better tomorrow.

**Comment by devongovett** [comment]
I hope you do too!

**Comment by auroranockert** [comment]
Thanks

**Comment by devongovett** [comment]
So it turned out workers were unnecessary. The `devon` branch now spreads out the decoding over the entire file rather than trying to decode as fast as possible, and this fixed the stuttering issue.
