### ISSUE TITLE
At the end of a stream, tries to read past end of buffer

### ISSUE THREAD

**Issue by devongovett** [audiocogs/alac.js#4]
Must be a partial frame issue...

`Uncaught TypeError: Cannot read property 'data' of undefined` in Stream.peekUInt8()

Ping @jensnockert.

**Comment by auroranockert** [comment]
I can haz stack trace?

**Comment by devongovett** [comment]
Hmmm... you're not seeing it?  Happens in just about every file for me when it decodes the last frame.  Stack traces are hard in workers, but it occurs on the normal streaming branch too... Here's what I've got:

![](http://f.cl.ly/items/1z1s0S0C0w1e290Y0J3M/Screen%20Shot%202011-12-06%20at%209.06.35%20AM.png)

**Comment by devongovett** [comment]
Doesn't seem to be happening anymore on the devon branch. Not sure what fixed it...
