### ISSUE TITLE
Fix description of project to reflect that it is not an encoder

### ISSUE THREAD

**Issue by synthesizerpatel** [audiocogs/alac.js#8]
I appreciate the work on the framework and the great resource you've provided - but I got really excited when I read 'encoder' in the title of the ALAC project only to find out after I went through all the steps to build from scratch to setup a work environment that there's no encoding component. It's not the end of the world but I did feel a bit sad. :(

Otherwise, keep up the great work! You guys rock!

**Comment by crackofdusk** [comment]
Fixed, thanks!
